use_frameworks!

platform :ios, '8.0'

target 'KSegmentControl_Example' do
  pod 'KSegmentControl', :path => '../'

  target 'KSegmentControl_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
